version: "3"
services:
  web:
    build:
      context: . # this means where is the file to copy
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
